# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1099, 726)
        self.gridLayout_4 = QtWidgets.QGridLayout(Window)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(Window)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dirEdit = QtWidgets.QLineEdit(Window)
        self.dirEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.dirEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dirEdit.setObjectName("dirEdit")
        self.horizontalLayout_9.addWidget(self.dirEdit)
        self.loadFilesButton = QtWidgets.QPushButton(Window)
        self.loadFilesButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadFilesButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loadFilesButton.setFont(font)
        self.loadFilesButton.setObjectName("loadFilesButton")
        self.horizontalLayout_9.addWidget(self.loadFilesButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 1, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Window)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.srcFileList = QtWidgets.QListWidget(Window)
        self.srcFileList.setObjectName("srcFileList")
        self.verticalLayout.addWidget(self.srcFileList)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Window)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.dstFileList = QtWidgets.QListWidget(Window)
        self.dstFileList.setObjectName("dstFileList")
        self.verticalLayout_2.addWidget(self.dstFileList)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(Window)
        self.label_8.setMinimumSize(QtCore.QSize(100, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.txtExtension = QtWidgets.QLineEdit(Window)
        self.txtExtension.setMinimumSize(QtCore.QSize(222, 30))
        self.txtExtension.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtExtension.setFont(font)
        self.txtExtension.setObjectName("txtExtension")
        self.horizontalLayout_8.addWidget(self.txtExtension)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Window)
        self.label_5.setMinimumSize(QtCore.QSize(100, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.txtPostfix = QtWidgets.QLineEdit(Window)
        self.txtPostfix.setMinimumSize(QtCore.QSize(222, 30))
        self.txtPostfix.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPostfix.setFont(font)
        self.txtPostfix.setObjectName("txtPostfix")
        self.horizontalLayout_4.addWidget(self.txtPostfix)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Window)
        self.label_7.setMinimumSize(QtCore.QSize(100, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.txtBy = QtWidgets.QLineEdit(Window)
        self.txtBy.setMinimumSize(QtCore.QSize(222, 30))
        self.txtBy.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtBy.setFont(font)
        self.txtBy.setObjectName("txtBy")
        self.horizontalLayout_5.addWidget(self.txtBy)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setMinimumSize(QtCore.QSize(100, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.txtPrefix = QtWidgets.QLineEdit(Window)
        self.txtPrefix.setMinimumSize(QtCore.QSize(222, 30))
        self.txtPrefix.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPrefix.setFont(font)
        self.txtPrefix.setObjectName("txtPrefix")
        self.horizontalLayout_6.addWidget(self.txtPrefix)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(Window)
        self.label_6.setMinimumSize(QtCore.QSize(100, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.txtReplace = QtWidgets.QLineEdit(Window)
        self.txtReplace.setMinimumSize(QtCore.QSize(222, 30))
        self.txtReplace.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtReplace.setFont(font)
        self.txtReplace.setObjectName("txtReplace")
        self.horizontalLayout_7.addWidget(self.txtReplace)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(Window)
        self.label_10.setMinimumSize(QtCore.QSize(150, 30))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.txtRegexRemove = QtWidgets.QLineEdit(Window)
        self.txtRegexRemove.setMinimumSize(QtCore.QSize(222, 30))
        self.txtRegexRemove.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtRegexRemove.setFont(font)
        self.txtRegexRemove.setText("")
        self.txtRegexRemove.setObjectName("txtRegexRemove")
        self.horizontalLayout.addWidget(self.txtRegexRemove)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblRegexKeep = QtWidgets.QLabel(Window)
        self.lblRegexKeep.setMinimumSize(QtCore.QSize(150, 30))
        self.lblRegexKeep.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblRegexKeep.setFont(font)
        self.lblRegexKeep.setObjectName("lblRegexKeep")
        self.horizontalLayout_2.addWidget(self.lblRegexKeep)
        self.txtRegexKeep = QtWidgets.QLineEdit(Window)
        self.txtRegexKeep.setMinimumSize(QtCore.QSize(222, 30))
        self.txtRegexKeep.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtRegexKeep.setFont(font)
        self.txtRegexKeep.setText("")
        self.txtRegexKeep.setObjectName("txtRegexKeep")
        self.horizontalLayout_2.addWidget(self.txtRegexKeep)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(Window)
        self.label_11.setMinimumSize(QtCore.QSize(150, 30))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.txtAppeDegit = QtWidgets.QLineEdit(Window)
        self.txtAppeDegit.setMinimumSize(QtCore.QSize(222, 30))
        self.txtAppeDegit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtAppeDegit.setFont(font)
        self.txtAppeDegit.setText("")
        self.txtAppeDegit.setObjectName("txtAppeDegit")
        self.horizontalLayout_3.addWidget(self.txtAppeDegit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 3, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pgBar = QtWidgets.QProgressBar(Window)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pgBar.setFont(font)
        self.pgBar.setProperty("value", 0)
        self.pgBar.setObjectName("pgBar")
        self.horizontalLayout_10.addWidget(self.pgBar)
        self.btnRename = QtWidgets.QPushButton(Window)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnRename.setFont(font)
        self.btnRename.setObjectName("btnRename")
        self.horizontalLayout_10.addWidget(self.btnRename)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 4, 0, 1, 2)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Vĩ Kudo Renamer"))
        self.label.setText(_translate("Window", "Last source directory"))
        self.loadFilesButton.setText(_translate("Window", "Load Files"))
        self.label_2.setText(_translate("Window", "File to rename"))
        self.label_3.setText(_translate("Window", "Renamed"))
        self.label_8.setText(_translate("Window", "Extension"))
        self.txtExtension.setPlaceholderText(_translate("Window", "extension"))
        self.label_5.setText(_translate("Window", "Postfix"))
        self.txtPostfix.setPlaceholderText(_translate("Window", "postfix"))
        self.label_7.setText(_translate("Window", "By"))
        self.txtBy.setPlaceholderText(_translate("Window", "by"))
        self.label_4.setText(_translate("Window", "Prefix"))
        self.txtPrefix.setPlaceholderText(_translate("Window", "prefix"))
        self.label_6.setText(_translate("Window", "Replace"))
        self.txtReplace.setPlaceholderText(_translate("Window", "replace"))
        self.label_10.setText(_translate("Window", "Regex Remove"))
        self.txtRegexRemove.setPlaceholderText(_translate("Window", "not implement"))
        self.lblRegexKeep.setText(_translate("Window", "Regex Keep"))
        self.txtRegexKeep.setPlaceholderText(_translate("Window", "keep"))
        self.label_11.setText(_translate("Window", "Append Degit"))
        self.txtAppeDegit.setPlaceholderText(_translate("Window", "not implement"))
        self.btnRename.setText(_translate("Window", "Rename"))

