# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1034, 693)
        self.gridLayout_3 = QtWidgets.QGridLayout(Window)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(Window)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.dirEdit = QtWidgets.QLineEdit(Window)
        self.dirEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.dirEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dirEdit.setObjectName("dirEdit")
        self.gridLayout_3.addWidget(self.dirEdit, 1, 0, 1, 2)
        self.loadFilesButton = QtWidgets.QPushButton(Window)
        self.loadFilesButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadFilesButton.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loadFilesButton.setFont(font)
        self.loadFilesButton.setObjectName("loadFilesButton")
        self.gridLayout_3.addWidget(self.loadFilesButton, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(Window)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.srcFileList = QtWidgets.QListWidget(self.widget)
        self.srcFileList.setObjectName("srcFileList")
        self.verticalLayout.addWidget(self.srcFileList)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.dstFileList = QtWidgets.QListWidget(self.widget1)
        self.dstFileList.setObjectName("dstFileList")
        self.verticalLayout_2.addWidget(self.dstFileList)
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 3)
        self.splitter_2 = QtWidgets.QSplitter(Window)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtPrefix = QtWidgets.QLineEdit(self.splitter_2)
        self.txtPrefix.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPrefix.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPrefix.setFont(font)
        self.txtPrefix.setObjectName("txtPrefix")
        self.gridLayout_3.addWidget(self.splitter_2, 3, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(Window)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_5 = QtWidgets.QLabel(self.splitter_3)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtPostfix = QtWidgets.QLineEdit(self.splitter_3)
        self.txtPostfix.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPostfix.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPostfix.setFont(font)
        self.txtPostfix.setObjectName("txtPostfix")
        self.gridLayout_3.addWidget(self.splitter_3, 3, 1, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(Window)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_6 = QtWidgets.QLabel(self.splitter_4)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txtReplace = QtWidgets.QLineEdit(self.splitter_4)
        self.txtReplace.setMinimumSize(QtCore.QSize(0, 30))
        self.txtReplace.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtReplace.setFont(font)
        self.txtReplace.setObjectName("txtReplace")
        self.gridLayout_3.addWidget(self.splitter_4, 4, 0, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(Window)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_7 = QtWidgets.QLabel(self.splitter_5)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txtBy = QtWidgets.QLineEdit(self.splitter_5)
        self.txtBy.setMinimumSize(QtCore.QSize(0, 30))
        self.txtBy.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtBy.setFont(font)
        self.txtBy.setObjectName("txtBy")
        self.gridLayout_3.addWidget(self.splitter_5, 4, 1, 1, 1)
        self.splitter_6 = QtWidgets.QSplitter(Window)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label_8 = QtWidgets.QLabel(self.splitter_6)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.txtExtension = QtWidgets.QLineEdit(self.splitter_6)
        self.txtExtension.setMinimumSize(QtCore.QSize(0, 30))
        self.txtExtension.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtExtension.setFont(font)
        self.txtExtension.setObjectName("txtExtension")
        self.gridLayout_3.addWidget(self.splitter_6, 5, 0, 1, 1)
        self.pgBar = QtWidgets.QProgressBar(Window)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pgBar.setFont(font)
        self.pgBar.setProperty("value", 0)
        self.pgBar.setObjectName("pgBar")
        self.gridLayout_3.addWidget(self.pgBar, 6, 0, 1, 2)
        self.btnRename = QtWidgets.QPushButton(Window)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnRename.setFont(font)
        self.btnRename.setObjectName("btnRename")
        self.gridLayout_3.addWidget(self.btnRename, 3, 2, 4, 1)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "RP Renamer"))
        self.label.setText(_translate("Window", "Last source directory"))
        self.loadFilesButton.setText(_translate("Window", "Load Files"))
        self.label_2.setText(_translate("Window", "File to rename"))
        self.label_3.setText(_translate("Window", "Renamed"))
        self.label_4.setText(_translate("Window", "Prefix"))
        self.txtPrefix.setPlaceholderText(_translate("Window", "prefix"))
        self.label_5.setText(_translate("Window", "Postfix"))
        self.txtPostfix.setPlaceholderText(_translate("Window", "postfix"))
        self.label_6.setText(_translate("Window", "Replace"))
        self.txtReplace.setPlaceholderText(_translate("Window", "replace"))
        self.label_7.setText(_translate("Window", "By"))
        self.txtBy.setPlaceholderText(_translate("Window", "by"))
        self.label_8.setText(_translate("Window", "Extension"))
        self.txtExtension.setPlaceholderText(_translate("Window", "extension"))
        self.btnRename.setText(_translate("Window", "Rename"))
